-- This file is auto-generated by scripts/gen_comm_lua.py from resources/positron-comms/connections-backend-openrpc.json.
-- Do not edit by hand.

local util = require("jet.ark.comm.util")

local M = {}

---@class jet.ark.comm.connections_backend.object_schema
---@field name string Name of the underlying object
---@field kind string The object type (table, catalog, schema)
---@field has_children? boolean Indicates if the object has children that can be listed. This property is optional and when omitted, it is assumed that the object may have children unless its kind is 'field'.

---@class jet.ark.comm.connections_backend.field_schema
---@field name string Name of the field
---@field dtype string The field data type

---@class jet.ark.comm.connections_backend.metadata_schema
---@field name string Connection name
---@field language_id string Language ID for the connections. Essentially just R or python
---@field host? string Connection host
---@field type? string Connection type
---@field code? string Code used to re-create the connection

---@class jet.ark.comm.connections_backend.list_objects.Params
---@field path jet.ark.comm.connections_backend.object_schema[] The path to object that we want to list children.

---List objects within a data source
---
---List objects within a data source, such as schemas, catalogs, tables and views.
---@param params jet.ark.comm.connections_backend.list_objects.Params
M.list_objects = function(params)
	return util.rpc_message("list_objects", params)
end

---@class jet.ark.comm.connections_backend.list_fields.Params
---@field path jet.ark.comm.connections_backend.object_schema[] The path to object that we want to list fields.

---List fields of an object
---
---List fields of an object, such as columns of a table or view.
---@param params jet.ark.comm.connections_backend.list_fields.Params
M.list_fields = function(params)
	return util.rpc_message("list_fields", params)
end

---@class jet.ark.comm.connections_backend.contains_data.Params
---@field path jet.ark.comm.connections_backend.object_schema[] The path to object that we want to check if it contains data.

---Check if an object contains data
---
---Check if an object contains data, such as a table or view.
---@param params jet.ark.comm.connections_backend.contains_data.Params
M.contains_data = function(params)
	return util.rpc_message("contains_data", params)
end

---@class jet.ark.comm.connections_backend.get_icon.Params
---@field path jet.ark.comm.connections_backend.object_schema[] The path to object that we want to get the icon.

---Get icon of an object
---
---Get icon of an object, such as a table or view.
---@param params jet.ark.comm.connections_backend.get_icon.Params
M.get_icon = function(params)
	return util.rpc_message("get_icon", params)
end

---@class jet.ark.comm.connections_backend.preview_object.Params
---@field path jet.ark.comm.connections_backend.object_schema[] The path to object that we want to preview.

---Preview object data
---
---Preview object data, such as a table or view.
---@param params jet.ark.comm.connections_backend.preview_object.Params
M.preview_object = function(params)
	return util.rpc_message("preview_object", params)
end

---@class jet.ark.comm.connections_backend.get_metadata.Params
---@field comm_id string The comm_id of the client we want to retrieve metdata for.

---Gets metadata from the connections
---
---A connection has tied metadata such as an icon, the host, etc.
---@param params jet.ark.comm.connections_backend.get_metadata.Params
M.get_metadata = function(params)
	return util.rpc_message("get_metadata", params)
end

return M
