-- This file is auto-generated by scripts/gen_comm_lua.py from resources/positron-comms/help-frontend-openrpc.json.
-- Do not edit by hand.

local util = require("jet.ark.comm.util")

local M = {}

---@class jet.ark.comm.help_frontend.show_help.Params
---@field content string The help content to show
---@field kind "html"|"markdown"|"url" The type of content to show
---@field focus boolean Whether to focus the Help pane when the content is displayed.

---Request to show help in the frontend
---@param params jet.ark.comm.help_frontend.show_help.Params
M.show_help = function(params)
	return util.rpc_message("show_help", params)
end

return M
