-- This file is auto-generated by scripts/gen_comm_lua.py from resources/positron-comms/help-backend-openrpc.json.
-- Do not edit by hand.

local util = require("jet.ark.comm.util")

local M = {}

---@class jet.ark.comm.help_backend.show_help_topic.Params
---@field topic string The help topic to show

---Look for and, if found, show a help topic.
---
---Requests that the help backend look for a help topic and, if found, show it. If the topic is found, it will be shown via a Show Help notification. If the topic is not found, no notification will be delivered.
---@param params jet.ark.comm.help_backend.show_help_topic.Params
M.show_help_topic = function(params)
	return util.rpc_message("show_help_topic", params)
end

return M
