-- This file is auto-generated by scripts/gen_comm_lua.py from resources/positron-comms/variables-frontend-openrpc.json.
-- Do not edit by hand.

local util = require("jet.ark.comm.util")

local M = {}

---@class jet.ark.comm.variables_frontend.update.Params
---@field assigned jet.ark.comm.variables_backend.variable[] An array of variables that have been newly assigned.
---@field unevaluated jet.ark.comm.variables_backend.variable[] An array of variables that were not evaluated for value updates.
---@field removed string[] An array of variable names that have been removed.
---@field version integer The version of the view (incremented with each update), or 0 if the backend doesn't track versions.

---Update variables
---
---Updates the variables in the current session.
---@param params jet.ark.comm.variables_frontend.update.Params
M.update = function(params)
	return util.rpc_message("update", params)
end

---@class jet.ark.comm.variables_frontend.refresh.Params
---@field variables jet.ark.comm.variables_backend.variable[] An array listing all the variables in the current session.
---@field length integer The number of variables in the current session.
---@field version integer The version of the view (incremented with each update), or 0 if the backend doesn't track versions.

---Refresh variables
---
---Replace all variables in the current session with the variables from the backend.
---@param params jet.ark.comm.variables_frontend.refresh.Params
M.refresh = function(params)
	return util.rpc_message("refresh", params)
end

return M
